# Development overrides
# This file is automatically loaded by docker-compose

services:
  app:
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  webserver:
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  # Note: Database is now Google Cloud SQL (external)
  # No local MySQL container needed
