# ArRahnu Auction Online - Production Docker Configuration
# For local development, use docker-compose.local.yaml instead
# Database will be provided by Google Cloud (Cloud SQL, Firestore, etc.)

services:
  # PHP Application
  app:
    build: ./php
    container_name: arrahnu_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - arrahnu_network
    # No database dependency - will connect to Google Cloud
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'PHP is running';"]
      timeout: 10s
      retries: 5
      start_period: 10s

  # Nginx Web Server
  nginx:
    build: ./nginx
    container_name: arrahnu_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - arrahnu_network
    depends_on:
      app:
        condition: service_healthy

networks:
  arrahnu_network:
    driver: bridge
