# ArRahnu Auction Online - Production Docker Configuration
# For local development, use docker-compose.local.yaml instead
# Database will be provided by Google Cloud (Cloud SQL, Firestore, etc.)

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./nginx/logs:/logs
    links:
      - php
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    command: bash -c "source /startup.sh && php-fpm"
    volumes:
      - ./:/var/www/html/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUN_FULL_SEEDING=false
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
    driver: local