services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - arrahnu-network
    restart: unless-stopped

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - PHP_FPM_USER=www-data
      - PHP_FPM_GROUP=www-data
    depends_on:
      - redis
    networks:
      - arrahnu-network
    restart: unless-stopped

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - arrahnu-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  arrahnu-network:
    driver: bridge